require("items.widgets.battery")
require("items.widgets.brightness")
require("items.widgets.volume")
require("items.widgets.bluetooth")
require("items.widgets.wifi")
require("items.widgets.cpu")
require("items.widgets.memory")
require("items.widgets.disk")
