#!/usr/bin/env sh
# this is just a shell script that runs when yabai starts
# it should contain global preferences for yabai
# for hotkeys - see skhdrc

# status bar configuration
yabai -m config status_bar                      on
yabai -m config status_bar_space_icon_strip     I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip      

# default options
yabai -m config layout bsp
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_border                on
yabai -m config window_border_placement      inset
yabai -m config window_border_width          3
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_color 0xff007aff
yabai -m config normal_window_border_color 0xff8e8e93