#!/bin/bash
# Generate host-specific Hyprland configuration from two independent axes:
#   1. Host type (desktop/laptop) — controls gaps, touchpad, visual effects
#   2. Keyboard layout (dvorak/qwerty) — controls keybinds and kb_variant
#
# Config files read:
#   ~/.config/hypr/host-type   — "desktop" (default) or "laptop"
#   ~/.config/hypr/kb-layout   — "dvorak" (default) or "qwerty"
#
# To change: echo "laptop" > ~/.config/hypr/host-type && hyprctl reload
#            echo "dvorak" > ~/.config/hypr/kb-layout && hyprctl reload

HYPR_DIR="$HOME/.config/hypr"
HOST_TYPE_FILE="$HYPR_DIR/host-type"
KB_LAYOUT_FILE="$HYPR_DIR/kb-layout"

# Read host type; default to desktop
if [[ -f "$HOST_TYPE_FILE" ]]; then
    HOST_TYPE="$(tr -d '[:space:]' < "$HOST_TYPE_FILE")"
else
    HOST_TYPE="desktop"
fi

# Read keyboard layout; default to dvorak
if [[ -f "$KB_LAYOUT_FILE" ]]; then
    KB_LAYOUT="$(tr -d '[:space:]' < "$KB_LAYOUT_FILE")"
else
    KB_LAYOUT="dvorak"
fi

# Validate host type
if [[ ! -d "$HYPR_DIR/hosts/$HOST_TYPE" ]]; then
    echo "WARNING: Unknown host type '$HOST_TYPE', falling back to desktop"
    HOST_TYPE="desktop"
fi

# Validate keyboard layout
if [[ ! -d "$HYPR_DIR/hosts/$KB_LAYOUT" ]]; then
    echo "WARNING: Unknown keyboard layout '$KB_LAYOUT', falling back to dvorak"
    KB_LAYOUT="dvorak"
fi

# Determine kb_variant for Hyprland's input section
case "$KB_LAYOUT" in
    dvorak) KB_VARIANT="dvorak" ;;
    *)      KB_VARIANT="" ;;
esac

echo "Host type: $HOST_TYPE | Keyboard layout: $KB_LAYOUT"

HEADER="# Auto-generated by update-host-config.sh — DO NOT EDIT MANUALLY
# Host type: $HOST_TYPE | Keyboard layout: $KB_LAYOUT
# To change: echo \"laptop\" or \"desktop\" > $HOST_TYPE_FILE
#            echo \"dvorak\" or \"qwerty\" > $KB_LAYOUT_FILE
"

# Generate host-specific settings (gaps, touchpad, visual effects)
echo "$HEADER" > "$HYPR_DIR/host-settings.conf"
cat "$HYPR_DIR/hosts/$HOST_TYPE/settings.conf" >> "$HYPR_DIR/host-settings.conf"

# Patch kb_variant based on keyboard layout selection
sed -i "s/kb_variant =.*/kb_variant = $KB_VARIANT/" "$HYPR_DIR/host-settings.conf"

echo "Generated host-settings.conf for $HOST_TYPE"

# Generate keyboard-layout-specific keybindings
echo "$HEADER" > "$HYPR_DIR/host-keybinds.conf"
cat "$HYPR_DIR/hosts/$KB_LAYOUT/keybinds.conf" >> "$HYPR_DIR/host-keybinds.conf"
echo "Generated host-keybinds.conf for $KB_LAYOUT"

echo "Host configuration updated ($HOST_TYPE/$KB_LAYOUT)"

# DPI-based monitor scaling — targets 140 effective DPI for consistent sizing.
# Uses hypr-scale.sh which computes valid scales mathematically (no probing).
SCALE_SCRIPT="$HYPR_DIR/hypr-scale.sh"
if [[ -x "$SCALE_SCRIPT" ]] && command -v hyprctl >/dev/null 2>&1; then
    "$SCALE_SCRIPT" auto 140
else
    echo "hypr-scale.sh or hyprctl not available, skipping DPI-based scaling"
fi
