#!/bin/bash
# Generate host-specific Hyprland configuration (settings + keybinds).
# Reads the host type from ~/.config/hypr/host-type, defaulting to "desktop".
# To change profile: echo "laptop" > ~/.config/hypr/host-type && hyprctl reload

HYPR_DIR="$HOME/.config/hypr"
HOST_TYPE_FILE="$HYPR_DIR/host-type"

# Read host type from config file; default to desktop if absent
if [[ -f "$HOST_TYPE_FILE" ]]; then
    HOST_TYPE="$(cat "$HOST_TYPE_FILE" | tr -d '[:space:]')"
else
    HOST_TYPE="desktop"
fi

# Validate host type has a matching profile directory
if [[ ! -d "$HYPR_DIR/hosts/$HOST_TYPE" ]]; then
    echo "WARNING: Unknown host type '$HOST_TYPE', falling back to desktop"
    HOST_TYPE="desktop"
fi

echo "Host type: $HOST_TYPE"

# Determine layout label from host type
case "$HOST_TYPE" in
    laptop)  LAYOUT="QWERTY" ;;
    *)       LAYOUT="Dvorak" ;;
esac

HEADER="# Auto-generated by update-host-config.sh — DO NOT EDIT MANUALLY
# Host type: $HOST_TYPE ($LAYOUT)
# To change: echo \"laptop\" or \"desktop\" > $HOST_TYPE_FILE
"

# Generate host-specific settings config
echo "$HEADER" > "$HYPR_DIR/host-settings.conf"
cat "$HYPR_DIR/hosts/$HOST_TYPE/settings.conf" >> "$HYPR_DIR/host-settings.conf"
echo "Generated host-settings.conf for $HOST_TYPE"

# Generate host-specific keybindings config
echo "$HEADER" > "$HYPR_DIR/host-keybinds.conf"
cat "$HYPR_DIR/hosts/$HOST_TYPE/keybinds.conf" >> "$HYPR_DIR/host-keybinds.conf"
echo "Generated host-keybinds.conf for $HOST_TYPE"

echo "Host configuration updated ($HOST_TYPE/$LAYOUT)"