#!/bin/bash

# Custom Rofi Script

BORDER="#ffd835"
SEPARATOR="#1c2028"
FOREGROUND="#EAEAEA"
BACKGROUND="#232832"
BACKGROUND_ALT="#1c2028"
HIGHLIGHT_BACKGROUND="#ffd835"
HIGHLIGHT_FOREGROUND="#1c2028"

BLACK="#000000"
WHITE="#ffffff"
RED="#e53935"
GREEN="#43a047"
YELLOW="#ffd835"
BLUE="#1e88e5"
MAGENTA="#FF00FF"
CYAN="#039be5"
PINK="#d81b60"
PURPLE="#8e24aa"
INDIGO="#3949ab"
TEAL="#00897b"
LIME="#c0ca33"
AMBER="#ffb300"
ORANGE="#fb8c00"
BROWN="#6d4c41"
GREY="#757575"
BLUE_GREY="#546e7a"
DEEP_PURPLE="#5e35b1"
DEEP_ORANGE="#f4511e"
LIGHT_BLUE="#039be5"
LIGHT_GREEN="#7cb342"

# Launch Rofi
MENU="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p 'System' \
-hide-scrollbar true \
-bw 3 \
-lines 5 \
-line-padding 10 \
-padding 0 \
-width 5 \
-xoffset -10 -yoffset 40 \
-location 3 \
-columns 1 \
-show-icons -icon-theme "Papirus" \
-font "Noto Sans 9" \
-color-enabled true \
-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
<<< ">> Lock|>> Logout|>> Suspend|>> Reboot|>> Shutdown")"
case "$MENU" in
  *Lock) i3lock-fancy ;;
  *Logout) i3-msg exit;;
  *Suspend) systemctl suspend ;;
  *Reboot) systemctl reboot ;;
  *Shutdown) systemctl -i poweroff
esac

# More Options
# -fullscreen \

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground
